//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by testtab.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_TESTTAB_DIALOG              102
#define IDD_YOUHUA_DIALOG               102
#define IDR_HTML_SYSTEMINFODLG          103
#define IDR_HTML_DLGCLEANRUBBISH        104
#define IDR_HTML_BEAUMASTER             105
#define IDR_MAINFRAME                   128
#define IDD_NETWORK                     130
#define IDD_TASKMGR                     133
#define IDR_MENUTASKMGR                 134
#define IDD_REGEDIT                     135
#define IDD_FILEEXPLORER                136
#define IDD_STARTMANGE                  137
#define IDD_SELECT                      139
#define IDI_ICON1                       145
#define IDI_ICON2                       146
#define IDI_ICON3                       147
#define IDI_ICON4                       148
#define IDI_ICON5                       149
#define IDI_ICON6                       150
#define IDR_MENU1                       151
#define IDD_DIALOG1                     153
#define IDB_BITMAP1                     154
#define IDB_BITMAP2                     155
#define IDD_DIALOGMAIN                  156
#define IDD_CLEARMASTER_DIALOG          157
#define IDD_MEIHUA_DIALOG               158
#define IDD_DIALOG_CLEARHISTORY         159
#define IDR_360SAFEZIP                  163
#define IDR_MENU2                       165
#define IDD_DIALOGCLEANRUBBISH          166
#define IDD_DIALOG_USBSHADU             169
#define IDD_DIALOG2                     170
#define IDD_DIALOGSYSTEMINFO            170
#define IDC_TAB1                        1000
#define IDC_LIST2                       1004
#define IDC_LIST1                       1007
#define IDC_CHECK1                      1009
#define IDC_CHECKRCLICK                 1010
#define IDC_CHECK2                      1010
#define IDC_TREE1                       1011
#define IDC_CHECKSOFTINFO               1011
#define IDC_CHECK_RENAME                1011
#define IDC_CHECK_CLEANGID              1011
#define IDC_CHECK_CLEARCOOKIES          1011
#define IDC_BUTTON1                     1012
#define IDC_CHECK_MODIFY                1012
#define IDC_BUTTONSTOP                  1012
#define IDC_CHECK_CLEAN_OLD             1012
#define IDC_CHECK_CLEARBWOSER           1012
#define IDC_CLEARMEM                    1013
#define IDC_CHECK_OTHERS                1013
#define IDC_CHECKBIGFILE                1013
#define IDC_BUTTON_YOUHUA               1013
#define IDC_CHECK5                      1013
#define IDC_BUTTON_MEIHUA               1014
#define IDC_CHECK6                      1014
#define IDC_PROGRESS1                   1018
#define IDC_CLEARREG                    1019
#define IDC_OPENREG                     1020
#define IDC_CHECKNOSTARTMENU            1021
#define IDC_STARTMONITOR                1023
#define IDC_BUTTON_CHOICEPATH           1024
#define IDC_BUTTON_CLEARALL             1025
#define IDC_CHECK7                      1025
#define IDC_LISTEN                      1026
#define IDC_CHECK8                      1026
#define IDC_BUTTON_STOP                 1027
#define IDC_BUTTON_OPTION               1028
#define IDC_BUTTON_EXPORT               1029
#define IDC_STATIC_PATH                 1030
#define IDC_BUTTON_SELECTALL            1032
#define IDC_BUTTON_REVERSELECT          1033
#define IDC_CHECK_ADDNEW                1034
#define IDC_CHECK__DELFILE              1035
#define IDC_BUTTON_SCAN                 1039
#define IDC_STATIC_STATE                1040
#define IDC_STATIC_USBSTATE             1040
#define IDC_STATIC_SCANPATH             1041
#define IDC_STATIC_SCANREGPATH          1042
#define IDC_BUTTON_STOPSCAN             1043
#define IDC_BUTTON2                     1044
#define IDC_BUTTONSTARTSCAN             1044
#define IDC_BUTTON_STARTCLEAR           1044
#define IDC_CHECK_DLL                   1044
#define IDC_BUTTON3                     1045
#define IDC_STATIC_VAILDSTARTMENU       1045
#define IDC_BUTTON_ENDCLEAR             1045
#define IDC_CHECK_CLEAN_TEMP            1054
#define IDC_CHECK_CELANLOG              1055
#define IDC_TREE2                       1056
#define IDC_BUTTON_CLEAR                1057
#define IDC_CHECK_CLEARINTERNET         1058
#define DC_EDSELDIR                     1062
#define IDC_LISTVIRUS                   1065
#define IDC_NUM_PROC                    1067
#define IDC_MEM_USE                     1068
#define ID_POPUP_32771                  32771
#define ID_POPUP_32772                  32772
#define ID_POPUP_32773                  32773
#define ID_LocatePro                    32774
#define ID_KILLPRO                      32775
#define ID_REFERSHLIST                  32776
#define ID_DDDD_32777                   32777
#define ID_DDDD_32778                   32778
#define ID_DLETEITEM                    32779
#define ID_OPENITEM                     32780
#define sda                             32781
#define sdaddsa                         32782
#define ID_POPUP_32783                  32783
#define ID_BAIDUSEARCH                  32784
#define ID_POPUP_32785                  32785
#define ID_POPUP_KILLAKK                32786
#define ID_POPUP_KILLALL                32787
#define ID_32788                        32788
#define ID_32789                        32789
#define ID_32790                        32790
#define ID_YOUHUA                       32791
#define ID_MEIHUA                       32792
#define ID_QINGLI                       32793
#define ID_CLEAR                        32794

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        171
#define _APS_NEXT_COMMAND_VALUE         32795
#define _APS_NEXT_CONTROL_VALUE         1070
#define _APS_NEXT_SYMED_VALUE           106
#endif
#endif
